//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fakulte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fakulte()
        {
            this.Bolum = new HashSet<Bolum>();
        }
    
        public int fak_id { get; set; }
        public string fak_name { get; set; }
        public string fak_adres { get; set; }
        public string fak_tel { get; set; }
        public string fak_fax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bolum> Bolum { get; set; }
    }
}
