//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.veritabani
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenci()
        {
            this.StajBilgi = new HashSet<StajBilgi>();
        }
    
        public int ogr_id { get; set; }
        [Required]
        public string ogr_tc { get; set; }
        [Required]
        public string ogr_ad { get; set; }
        [Required]
        public string ogr_soyad { get; set; }
        [Required]
        public string ogr_no { get; set; }
        [Required]
        public bool ogr_sigorta { get; set; }
        [Required]
        public string ogr_adres { get; set; }
        [Required]
        public string ogr_tel { get; set; }
        [Required]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,4}", ErrorMessage = "Yanlýþ Mail Formatý")]
        public string ogr_mail { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}", NullDisplayText = "Dogum Tarihi Girilmemiþ")]
        [Required]
        [RegularExpression(@"^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d$", ErrorMessage = "dd-mm-yyyy formatýnda girin")]


        public string ogr_dogum { get; set; }
        [Required]
        public string ogr_bolumkod { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string ogr_parola { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StajBilgi> StajBilgi { get; set; }
    }
}
